version: '3'
services:
  worker:
    build: ./DockerFiles/Worker
    ports:
    - ${LOCAL_IP}:${LALAMOVE_SERVER_PORT}:80
    - ${LOCAL_IP}:${PHP_SSH_PORT}:22
    depends_on:
    - mysql
    links:
    - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: lalamove
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      LOCAL_DEV_DIR: ${LOCAL_DEV_DIR}
      VENDOR_DIR: ${VENDOR_DIR}
    volumes:
    - ${LOCAL_DEV_DIR}:/var/www
  mysql:
    build: ./DockerFiles/Mysql
    ports:
    - ${LOCAL_IP}:${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: root